# Generated by Django 6.0.1 on 2026-02-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='service_features',
            field=models.TextField(blank=True, help_text='One service feature per line', null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='service_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
