# Generated by Django 6.0.1 on 2026-02-15 16:07

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_additionalonly_addon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalonly',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MaxValueValidator(Decimal('99999999.99'))]),
        ),
        migrations.AlterField(
            model_name='addon',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MaxValueValidator(Decimal('99999999.99'))]),
        ),
        migrations.AlterField(
            model_name='addon',
            name='solo_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MaxValueValidator(Decimal('99999999.99'))]),
        ),
    ]
