# Generated by Django 6.0.1 on 2026-02-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_additionalonly_price_alter_addon_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='service_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
