# Generated by Django 6.0.1 on 2026-02-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_package_service_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalonly',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='additional/'),
        ),
        migrations.AddField(
            model_name='addon',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='addons/'),
        ),
    ]
