# Generated by Django 6.0.2 on 2026-03-04 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_chatsession_chatmessage_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='number_of_guests',
        ),
    ]
