# Generated by Django 6.0.2 on 2026-03-04 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_booking_number_of_guests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='event_type',
        ),
    ]
