# Generated by Django 6.0.2 on 2026-03-04 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_booking_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='event_type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
