# Generated by Django 6.0.2 on 2026-03-05 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_booking_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reference_image',
            field=models.ImageField(blank=True, null=True, upload_to='booking_references/'),
        ),
    ]
