# Generated by Django 6.0.2 on 2026-03-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_reviewimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='admin_notified',
            field=models.BooleanField(default=False),
        ),
    ]
