# Generated by Django 6.0.2 on 2026-03-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_booking_admin_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='admin_notif_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
