# Generated by Django 6.0.2 on 2026-03-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_additionalonly_price_alter_addon_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='event_location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='booking',
            name='package_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
