# Generated by Django 6.0.2 on 2026-03-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_adminnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='package_type',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
