# Generated by Django 6.0.2 on 2026-03-17 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_userdesign'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdesign',
            name='base_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_designs', to='app.package'),
        ),
    ]
