# Generated by Django 6.0.2 on 2026-03-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_gallerycategory_galleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='addon',
            name='service_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
