# Generated by Django 6.0.2 on 2026-03-23 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_servicechargeconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='service_features',
        ),
        migrations.RemoveField(
            model_name='package',
            name='service_notes',
        ),
    ]
