# Generated by Django 6.0.2 on 2026-03-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_remove_package_service_features_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancel_request_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='edit_original_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='edit_request_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
