# Generated by Django 6.0.2 on 2026-03-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_booking_cancel_request_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='admin_denial_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
