# Generated by Django 6.0.2 on 2026-03-25 15:42

from pathlib import Path
import django.db.models.deletion
from django.db import migrations, models


def seed_canvas_assets(apps, schema_editor):
    CanvasCategory = apps.get_model('app', 'CanvasCategory')
    CanvasAsset = apps.get_model('app', 'CanvasAsset')

    if CanvasAsset.objects.exists():
        return

    premium_root = Path(__file__).resolve().parents[2] / 'static' / 'images' / 'canvas' / 'premium'
    if not premium_root.exists():
        return

    folder_to_category = {
        'frames': 'Frames / Structures',
        'balloons': 'Balloons',
        'decorations': 'Decorations',
        'furniture': 'Furniture',
        'party': 'Party Items',
        'themes': 'Theme Objects',
        'texts': 'Text & Signs',
    }
    folder_default_size = {
        'frames': (200, 200),
        'balloons': (80, 80),
        'decorations': (100, 100),
        'furniture': (90, 110),
        'party': (90, 90),
        'themes': (100, 120),
        'texts': (150, 80),
    }

    categories_by_name = {}
    category_order = 0

    for folder_name in sorted(folder_to_category.keys()):
        folder_path = premium_root / folder_name
        if not folder_path.exists():
            continue

        category_name = folder_to_category[folder_name]
        category = CanvasCategory.objects.create(
            name=category_name,
            order=category_order,
            is_active=True,
        )
        categories_by_name[category_name] = category
        category_order += 1

        width_val, height_val = folder_default_size.get(folder_name, (150, 150))
        files = sorted(
            [p for p in folder_path.iterdir() if p.is_file() and p.suffix.lower() in {'.svg', '.png', '.jpg', '.jpeg', '.webp'}],
            key=lambda x: x.name.lower()
        )

        for sort_order, file_path in enumerate(files):
            stem = file_path.stem.replace('_', ' ').replace('-', ' ').strip()
            label = stem.title() if stem else file_path.name
            static_path = f"images/canvas/premium/{folder_name}/{file_path.name}"
            CanvasAsset.objects.create(
                category=category,
                label=label,
                subgroup=f"{category_name} Assets",
                static_path=static_path,
                item_type='image',
                width=width_val,
                height=height_val,
                sort_order=sort_order,
                is_active=True,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_concernticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanvasCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower number = shown first')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Canvas Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CanvasAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150)),
                ('subgroup', models.CharField(blank=True, default='', max_length=120)),
                ('image', models.ImageField(blank=True, null=True, upload_to='canvas_assets/')),
                ('static_path', models.CharField(blank=True, default='', help_text='Optional static path (e.g. images/canvas/premium/frames/round_arch.svg)', max_length=255)),
                ('item_type', models.CharField(default='image', max_length=20)),
                ('width', models.PositiveIntegerField(default=150)),
                ('height', models.PositiveIntegerField(default=150)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower number = shown first')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='app.canvascategory')),
            ],
            options={
                'ordering': ['category__order', 'subgroup', 'sort_order', 'id'],
            },
        ),
        migrations.RunPython(seed_canvas_assets, migrations.RunPython.noop),
    ]
