# Generated by Django 6.0.2 on 2026-03-25 16:45

import django.db.models.deletion
from django.db import migrations, models


def backfill_canvas_labels(apps, schema_editor):
    CanvasAsset = apps.get_model('app', 'CanvasAsset')
    CanvasLabel = apps.get_model('app', 'CanvasLabel')

    label_cache = {}

    for asset in CanvasAsset.objects.select_related('category').all().order_by('category_id', 'sort_order', 'id'):
        label_name = (asset.subgroup or '').strip() or 'General'
        key = (asset.category_id, label_name.lower())
        label_obj = label_cache.get(key)
        if label_obj is None:
            current_count = CanvasLabel.objects.filter(category_id=asset.category_id).count()
            label_obj, _ = CanvasLabel.objects.get_or_create(
                category_id=asset.category_id,
                name=label_name,
                defaults={'order': current_count, 'is_active': True},
            )
            label_cache[key] = label_obj

        asset.label_ref_id = label_obj.id
        asset.subgroup = label_obj.name
        asset.save(update_fields=['label_ref', 'subgroup'])


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_canvascategory_canvasasset'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanvasLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower number = shown first')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='app.canvascategory')),
            ],
            options={
                'ordering': ['category__order', 'order', 'name'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.AddField(
            model_name='canvasasset',
            name='label_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='app.canvaslabel'),
        ),
        migrations.RunPython(backfill_canvas_labels, migrations.RunPython.noop),
    ]
