# Generated by Django 6.0.2 on 2026-03-25 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_canvaslabel_canvasasset_label_ref'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='canvasasset',
            options={'ordering': ['category__order', 'label_ref__order', 'subgroup', 'sort_order', 'id']},
        ),
    ]
