# Generated by Django 6.0.2 on 2026-03-25 16:54

from django.db import migrations, models


def normalize_canvas_orders(apps, schema_editor):
    CanvasCategory = apps.get_model('app', 'CanvasCategory')
    CanvasLabel = apps.get_model('app', 'CanvasLabel')
    CanvasCategory.objects.filter(order=0).update(order=1)
    CanvasLabel.objects.filter(order=0).update(order=1)


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_alter_canvasasset_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvascategory',
            name='order',
            field=models.PositiveIntegerField(default=1, help_text='Lower number = shown first'),
        ),
        migrations.AlterField(
            model_name='canvaslabel',
            name='order',
            field=models.PositiveIntegerField(default=1, help_text='Lower number = shown first'),
        ),
        migrations.RunPython(normalize_canvas_orders, migrations.RunPython.noop),
    ]
