# Generated by Django 6.0.2 on 2026-04-20 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_user_email_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(blank=True, default='', max_length=255)),
                ('hero_subtitle', models.TextField(blank=True, default='')),
                ('story_label', models.CharField(blank=True, default='', max_length=255)),
                ('story_title', models.CharField(blank=True, default='', max_length=255)),
                ('story_paragraph_1', models.TextField(blank=True, default='')),
                ('story_paragraph_2', models.TextField(blank=True, default='')),
                ('story_image', models.ImageField(blank=True, null=True, upload_to='about_content/')),
                ('stat_events_styled', models.CharField(blank=True, default='', max_length=50)),
                ('stat_year_founded', models.CharField(blank=True, default='', max_length=50)),
                ('stat_satisfaction', models.CharField(blank=True, default='', max_length=50)),
                ('mission_label', models.CharField(blank=True, default='', max_length=255)),
                ('mission_title', models.CharField(blank=True, default='', max_length=255)),
                ('mission_paragraph_1', models.TextField(blank=True, default='')),
                ('mission_paragraph_2', models.TextField(blank=True, default='')),
                ('mission_image', models.ImageField(blank=True, null=True, upload_to='about_content/')),
                ('values_title', models.CharField(blank=True, default='', max_length=255)),
                ('values_subtitle', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'About Content',
            },
        ),
        migrations.CreateModel(
            name='GCashConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downpayment_percent', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('gcash_number', models.CharField(blank=True, default='', max_length=100)),
                ('gcash_name', models.CharField(blank=True, default='', max_length=255)),
                ('instructions', models.TextField(blank=True, default='')),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='gcash_config/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'GCash Configuration',
                'verbose_name_plural': 'GCash Configuration',
            },
        ),
        migrations.CreateModel(
            name='HomeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(blank=True, default='', max_length=255)),
                ('hero_subheadline', models.TextField(blank=True, default='')),
                ('hero_primary_cta_text', models.CharField(blank=True, default='', max_length=100)),
                ('hero_secondary_cta_text', models.CharField(blank=True, default='', max_length=100)),
                ('hero_main_image', models.ImageField(blank=True, null=True, upload_to='home_content/')),
                ('hero_float_top_image', models.ImageField(blank=True, null=True, upload_to='home_content/')),
                ('hero_float_bottom_image', models.ImageField(blank=True, null=True, upload_to='home_content/')),
                ('stat_events_styled', models.CharField(blank=True, default='', max_length=50)),
                ('stat_rating', models.CharField(blank=True, default='', max_length=50)),
                ('stat_satisfaction', models.CharField(blank=True, default='', max_length=50)),
                ('stat_response_time', models.CharField(blank=True, default='', max_length=50)),
                ('why_choose_title', models.CharField(blank=True, default='', max_length=255)),
                ('why_choose_subtitle', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Home Content',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('features', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='gcash_reference_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='gcash_sender_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('downpayment', 'Downpayment'), ('full', 'Full Payment'), ('balance', 'Balance')], default='full', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='paymongo_checkout_session_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='paymongo_checkout_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='payment',
            name='paymongo_payment_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='payment_receipts/'),
        ),
        migrations.AddField(
            model_name='payment',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='is_testimonial',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('gcash', 'GCash'), ('card', 'Card'), ('paypal', 'PayPal'), ('paymongo_card', 'PayMongo Card'), ('paymongo_gcash', 'PayMongo GCash'), ('paymongo_grabpay', 'PayMongo GrabPay')], max_length=30),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
        migrations.CreateModel(
            name='AboutValueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('icon_class', models.CharField(blank=True, default='fas fa-star', max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('about_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='app.aboutcontent')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomeFeatureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('icon_class', models.CharField(blank=True, default='fas fa-star', max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('home_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='app.homecontent')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
