# Generated by Django 6.0.2 on 2026-04-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_aboutcontent_gcashconfig_homecontent_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial Payment'), ('paid', 'Paid')], default='pending', max_length=15),
        ),
    ]
