# Generated by Django 6.0.2 on 2026-04-21 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pending_payment', 'Pending Payment'), ('confirmed', 'Confirmed'), ('cancel_requested', 'Cancel Requested'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
    ]
