# Generated by Django 6.0.2 on 2026-04-21 05:46

from django.db import migrations, models


def update_payment_statuses(apps, schema_editor):
    Payment = apps.get_model('app', 'Payment')
    
    # Update 'paid' to 'verified'
    Payment.objects.filter(payment_status='paid').update(payment_status='verified')
    
    # Update 'failed' to 'rejected'
    Payment.objects.filter(payment_status='failed').update(payment_status='rejected')


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_alter_booking_status'),
    ]

    operations = [
        migrations.RunPython(update_payment_statuses, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
