# Generated by Django 6.0.1 on 2026-04-22 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_alter_payment_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homecontent',
            name='hero_primary_cta_text',
        ),
        migrations.RemoveField(
            model_name='homecontent',
            name='hero_secondary_cta_text',
        ),
    ]
