# Generated by Django 6.0.2 on 2026-04-22 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_remove_homecontent_hero_primary_cta_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(blank=True, default='', max_length=255)),
                ('hero_subtitle', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Service Content',
            },
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('features', models.TextField(help_text='One feature per line')),
                ('image', models.ImageField(blank=True, null=True, upload_to='service_content/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='app.servicecontent')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
