# Generated by Django 6.0.2 on 2026-04-22 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_servicecontent_serviceitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceItem',
        ),
    ]
