# Generated by Django 6.0.2 on 2026-04-22 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_delete_serviceitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='features',
        ),
    ]
