# Generated by Django 6.0.2 on 2026-04-23 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_remove_service_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatModerationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(choices=[('profanity', 'Profanity'), ('toxicity', 'Toxicity')], default='profanity', max_length=20)),
                ('matched_terms', models.CharField(blank=True, default='', max_length=255)),
                ('message_excerpt', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_moderation_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Moderation Event',
                'verbose_name_plural': 'Chat Moderation Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatModerationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banned_until', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_ban_ended_at', models.DateTimeField(blank=True, null=True)),
                ('total_violations', models.PositiveIntegerField(default=0)),
                ('total_bans', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_moderation_state', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Moderation State',
                'verbose_name_plural': 'Chat Moderation States',
            },
        ),
    ]
