# Generated by Django 5.0.6 on 2026-09-05 03:32

from django.db import migrations, models


def mark_existing_support_chats(apps, schema_editor):
    ChatSession = apps.get_model('app', 'ChatSession')
    ChatSession.objects.filter(
        models.Q(status__in=['pending_admin', 'active_admin'])
        | models.Q(assigned_admin__isnull=False)
        | models.Q(last_client_message_at__isnull=False)
    ).update(is_admin_support=True)
    ChatSession.objects.filter(status='pending_admin').update(status='active_admin')


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_chatmessage_is_read_chatmessage_read_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_attachments/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='image_original_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='is_admin_support',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.RunPython(mark_existing_support_chats, migrations.RunPython.noop),
    ]
