# Generated by Django 5.0.6 on 2026-09-06 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0066_alter_chatnotification_id_alter_messagereaction_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuidelinePageContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_key', models.CharField(choices=[('guidelines', 'Booking Guidelines'), ('terms', 'Terms & Conditions'), ('privacy', 'Privacy Policy')], max_length=20, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('intro', models.TextField(blank=True, default='')),
                ('attachment_label', models.CharField(blank=True, default='', max_length=255)),
                ('attachment_url', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Guideline Page Content',
                'verbose_name_plural': 'Guideline Page Contents',
            },
        ),
        migrations.CreateModel(
            name='GuidelineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, default='', max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.guidelinepagecontent')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
