# Generated by Django 5.0.6 on 2026-09-07 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0068_seed_guideline_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecontent',
            name='cta_primary_text',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='cta_secondary_text',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='cta_subtitle',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='cta_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='faq_subtitle',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='faq_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='how_it_works_label',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='how_it_works_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='how_it_works_title_accent',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='occasion_chips',
            field=models.CharField(blank=True, default='', help_text='Comma-separated list, e.g. Birthdays, Weddings, Corporate Events', max_length=500),
        ),
        migrations.CreateModel(
            name='HomeFaqItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField(blank=True, default='')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('home_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='app.homecontent')),
            ],
            options={
                'verbose_name_plural': 'Home FAQ Items',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomeHowItWorksStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('icon_class', models.CharField(blank=True, default='fas fa-star', max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('home_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='how_it_works_steps', to='app.homecontent')),
            ],
            options={
                'verbose_name_plural': 'Home How It Works Steps',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
