# Generated by Django 5.0.6 on 2026-09-08 12:47

import django.db.models.deletion
from django.db import migrations, models


def seed_journey_items(apps, schema_editor):
    """Seed the default 4 "Our Journey" steps for the About page."""
    AboutContent = apps.get_model('app', 'AboutContent')
    AboutJourneyItem = apps.get_model('app', 'AboutJourneyItem')

    if AboutJourneyItem.objects.exists():
        return

    content = AboutContent.objects.first()
    if content is None:
        content = AboutContent.objects.create()

    defaults = [
        (
            'The Beginning',
            'Every celebration starts with a spark.',
            'Balloorina.ph was created from a simple love for styling celebrations. '
            'What began in 2020 as a small home studio grew from one wish — to make '
            'every moment feel special, no matter the size of the event.',
        ),
        (
            'Learning the Craft',
            'Listening before styling.',
            'Before every setup, we take time to understand the occasion — the theme, '
            'the colors, and the story behind the celebration — so every balloon '
            'design feels personal and true to the client.',
        ),
        (
            'Growing the Dream',
            'From a small studio to a trusted team.',
            'Word of mouth carried our work from intimate family parties to weddings '
            'and corporate events across Metro Manila — one beautifully styled setup '
            'at a time.',
        ),
        (
            'Where We Are Now',
            'Styling moments that matter.',
            'Today, Balloorina.ph continues to craft clean, elegant, and photo-worthy '
            'setups, helping hundreds of clients celebrate life\u2019s biggest moments '
            'with confidence and style.',
        ),
    ]

    for order, (caption, title, description) in enumerate(defaults):
        AboutJourneyItem.objects.create(
            about_content=content,
            caption=caption,
            title=title,
            description=description,
            display_order=order,
            is_active=True,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0072_aboutcontent_story_visuals'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcontent',
            name='journey_subtitle',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='journey_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='AboutJourneyItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, default='', max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('about_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_items', to='app.aboutcontent')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.RunPython(seed_journey_items, migrations.RunPython.noop),
    ]
