# Generated by Django 5.0.6 on 2026-09-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0073_aboutjourney_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='best_for',
            field=models.CharField(blank=True, default='', help_text="Short text used in the Services page comparison table, e.g. 'Kids parties and milestones'.", max_length=255),
        ),
        migrations.AddField(
            model_name='service',
            name='features',
            field=models.TextField(blank=True, default='', help_text='One feature per line. Shown as a checklist under the service on the Services page.'),
        ),
    ]
