# Generated by Django 5.0.6 on 2026-09-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0074_service_best_for_service_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecontent',
            name='hero_label',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
