# Generated by Django 5.0.6 on 2026-09-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0075_servicecontent_hero_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='description',
            field=models.TextField(blank=True, help_text='Short line shown under the package name on the Packages page', null=True),
        ),
    ]
