# Generated by Django 5.0.6 on 2026-09-14 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0076_package_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homecontent',
            name='cta_primary_text',
        ),
        migrations.RemoveField(
            model_name='homecontent',
            name='cta_secondary_text',
        ),
        migrations.RemoveField(
            model_name='homecontent',
            name='hero_float_bottom_image',
        ),
        migrations.RemoveField(
            model_name='homecontent',
            name='hero_float_top_image',
        ),
        migrations.RemoveField(
            model_name='homecontent',
            name='hero_main_image',
        ),
        migrations.AddField(
            model_name='homecontent',
            name='hero_label',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
