# Generated by Django 5.0.6 on 2026-09-14 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0080_reviewreply'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Balloorina', max_length=150)),
                ('contact_email', models.CharField(blank=True, default='', max_length=255)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=50)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('facebook_link', models.URLField(blank=True, default='')),
                ('instagram_link', models.URLField(blank=True, default='')),
                ('booking_lead_time_days', models.PositiveIntegerField(default=0, help_text='Minimum number of days between today and a booking date. 0 = no lead time requirement.')),
                ('admin_emails_for_notifications', models.CharField(blank=True, default='', help_text='Comma-separated email addresses that receive admin alert emails. Leave empty to disable.', max_length=500)),
                ('email_notifications_enabled', models.BooleanField(default=True, help_text='Send email alerts to admin when new bookings, payments, or concerns come in.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
