# Generated by Django 5.0.6 on 2026-09-20 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0082_chatmessage_is_pinned_chatmessage_pinned_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='New accounts must verify their email before logging in.'),
        ),
    ]
