# Generated by Django 5.0.6 on 2026-09-20 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0083_alter_user_email_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiImageFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=500)),
                ('prompt', models.TextField(blank=True, default='')),
                ('rating', models.SmallIntegerField(choices=[(1, 'Like'), (-1, 'Dislike')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_image_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'image_url')},
            },
        ),
    ]
