from django.urls import path

from .views import (
    AboutPageView,
    GalleryPageView,
    GuidelinesPageView,
    HomePageView,
    PackagePageView,
    ServicesPageView,
    admin_about_content,
    admin_about_value_create,
    admin_about_value_delete,
    admin_about_value_edit,
    admin_additional_create,
    admin_additional_delete,
    admin_additional_detail,
    admin_additional_edit,
    admin_addon_create,
    admin_addon_delete,
    admin_addon_detail,
    admin_addon_edit,
    admin_analytics,
    admin_analytics_export_excel,
    admin_analytics_export_pdf,
    admin_audit_log_list,
    admin_booking_action,
    admin_booking_detail,
    admin_booking_list,
    admin_calendar,
    admin_cancel_action,
    admin_canvas_asset_create,
    admin_canvas_asset_delete,
    admin_canvas_asset_detail,
    admin_canvas_asset_edit,
    admin_canvas_assets,
    admin_canvas_category_create,
    admin_canvas_category_delete,
    admin_canvas_category_edit,
    admin_canvas_label_create,
    admin_canvas_label_delete,
    admin_canvas_label_edit,
    admin_concern_update,
    admin_concerns,
    admin_edit_action,
    admin_gallery,
    admin_gallery_category_create,
    admin_gallery_category_delete,
    admin_gallery_category_edit,
    admin_gallery_image_create,
    admin_gallery_image_delete,
    admin_gallery_image_detail,
    admin_gallery_image_edit,
    admin_gcash_config,
    admin_home_content,
    admin_home_feature_create,
    admin_home_feature_delete,
    admin_home_feature_edit,
    admin_package_create,
    admin_package_delete,
    admin_package_detail,
    admin_package_edit,
    admin_package_list,
    admin_payment_action,
    admin_payment_detail,
    admin_payment_list,
    admin_profile,
    admin_reports,
    admin_review_toggle_testimonial,
    admin_reviews,
    admin_service_charge_update,
    admin_service_create,
    admin_service_delete,
    admin_service_detail,
    admin_service_edit,
    admin_service_list,
    admin_user_delete,
    admin_user_edit,
    admin_user_list,
    admin_user_toggle_active,
    booking_page,
    change_password,
    chat_api,
    chat_clear,
    chat_history,
    chat_sessions,
    clear_all_notifications,
    create_booking,
    create_paymongo_checkout,
    customer_profile,
    dashboard,
    delete_booking,
    delete_review,
    delete_user_design,
    design_canvas_page,
    download_payment_receipt_pdf,
    edit_booking,
    edit_review,
    forgot_password_request,
    hide_notification,
    like_review,
    mark_customer_notification_read,
    mark_notifications_read,
    my_designs_page,
    my_payments,
    my_profile,
    my_reviews,
    package,
    password_reset_confirm,
    payment_cancel,
    payment_page,
    payment_success,
    paymongo_cancel,
    paymongo_success,
    paymongo_webhook,
    register,
    rename_user_design,
    report_concern,
    request_cancel_booking,
    request_edit_booking,
    reviews_page,
    save_user_design,
    select_design_type,
    submit_payment,
    submit_review,
    update_my_profile,
    user_login,
    user_logout,
    verify_email,
    view_booking,
)

urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
    path("about/", AboutPageView.as_view(), name="about"),
    path("services/", ServicesPageView.as_view(), name="services"),
    path("guidelines/", GuidelinesPageView.as_view(), name="guidelines"),
    path("package/", PackagePageView.as_view(), name="package"),
    path("gallery/", GalleryPageView.as_view(), name="gallery"),
    # My Designs Dashboard
    path("my-designs/", my_designs_page, name="my_designs"),
    path("select-design/", select_design_type, name="select_design_type"),
    path("my-designs/save/", save_user_design, name="save_user_design"),
    path("my-designs/rename/<int:id>/", rename_user_design, name="rename_user_design"),
    path("my-designs/delete/<int:id>/", delete_user_design, name="delete_user_design"),
    path("register/", register, name="register"),
    path("verify-email/<uidb64>/<token>/", verify_email, name="verify_email"),
    path("login/", user_login, name="login"),
    path("forgot-password/", forgot_password_request, name="forgot_password"),
    path(
        "reset-password/<uidb64>/<token>/",
        password_reset_confirm,
        name="password_reset_confirm",
    ),
    path("logout/", user_logout, name="logout"),
    path("dashboard/", dashboard, name="dashboard"),
    path(
        "customer/", customer_profile, name="customer_profile"
    ),  # This will act as My Bookings
    path("my-payments/", my_payments, name="my_payments"),
    path(
        "my-payments/<int:payment_id>/receipt-pdf/",
        download_payment_receipt_pdf,
        name="download_payment_receipt_pdf",
    ),
    path("my-profile/", my_profile, name="my_profile"),
    path("update-my-profile/", update_my_profile, name="update_my_profile"),
    path("my-reviews/", my_reviews, name="my_reviews"),
    path("report-concern/", report_concern, name="report_concern"),
    path("change-password/", change_password, name="change_password"),
    path("admin-profile/", admin_profile, name="admin_profile"),
    path("reviews/", reviews_page, name="reviews"),
    path("reviews/<int:review_id>/like/", like_review, name="like_review"),
    path("reviews/<int:review_id>/edit/", edit_review, name="edit_review"),
    path("reviews/<int:review_id>/delete/", delete_review, name="delete_review"),
    # Booking
    path("booking/", booking_page, name="booking_page"),
    path("booking/create/", create_booking, name="create_booking"),
    path("booking/<int:id>/", view_booking, name="view_booking"),
    path("booking/<int:id>/edit/", edit_booking, name="edit_booking"),
    path("booking/<int:id>/delete/", delete_booking, name="delete_booking"),
    path("booking/<int:id>/review/", submit_review, name="submit_review"),
    path("design/", design_canvas_page, name="design_canvas"),
    # Admin Booking Approval
    path("staff/bookings/", admin_booking_list, name="admin_booking_list"),
    path(
        "staff/bookings/<int:id>/view/",
        admin_booking_detail,
        name="admin_booking_detail",
    ),
    path(
        "staff/bookings/<int:id>/<str:action>/",
        admin_booking_action,
        name="admin_booking_action",
    ),
    path(
        "booking/<int:id>/cancel/",
        request_cancel_booking,
        name="request_cancel_booking",
    ),
    path(
        "staff/cancel-requests/<int:id>/<str:action>/",
        admin_cancel_action,
        name="admin_cancel_action",
    ),
    path(
        "booking/<int:id>/request-edit/",
        request_edit_booking,
        name="request_edit_booking",
    ),
    path(
        "staff/bookings/<int:id>/edit/<str:action>/",
        admin_edit_action,
        name="admin_edit_action",
    ),
    # Admin User Management
    path("staff/users/", admin_user_list, name="admin_user_list"),
    path("staff/users/<int:id>/edit/", admin_user_edit, name="admin_user_edit"),
    path(
        "staff/users/<int:id>/toggle/",
        admin_user_toggle_active,
        name="admin_user_toggle",
    ),
    path("staff/users/<int:id>/delete/", admin_user_delete, name="admin_user_delete"),
    # Audit Log
    path("staff/audit-log/", admin_audit_log_list, name="admin_audit_log"),
    # Admin Reviews
    path("staff/reviews/", admin_reviews, name="admin_reviews"),
    path(
        "staff/reviews/<int:id>/testimonial-toggle/",
        admin_review_toggle_testimonial,
        name="admin_review_toggle_testimonial",
    ),
    # Concerns and Reports Analytics
    path("staff/reports/", admin_reports, name="admin_reports"),
    path("staff/concerns/", admin_concerns, name="admin_concerns"),
    path("staff/analytics/", admin_analytics, name="admin_analytics"),
    path(
        "staff/analytics/export/excel/",
        admin_analytics_export_excel,
        name="admin_analytics_export_excel",
    ),
    path(
        "staff/analytics/export/pdf/",
        admin_analytics_export_pdf,
        name="admin_analytics_export_pdf",
    ),
    path(
        "staff/concerns/<int:id>/update/",
        admin_concern_update,
        name="admin_concern_update",
    ),
    # Admin Calendar & Notifications
    path("staff/calendar/", admin_calendar, name="admin_calendar"),
    path(
        "staff/notifications/read/",
        mark_notifications_read,
        name="mark_notifications_read",
    ),
    path(
        "staff/notifications/<int:id>/hide/",
        hide_notification,
        name="hide_notification",
    ),
    # Admin Package Management
    path("staff/services/", admin_service_list, name="admin_service_list"),
    path("staff/services/create/", admin_service_create, name="admin_service_create"),
    path(
        "staff/services/<int:id>/view/",
        admin_service_detail,
        name="admin_service_detail",
    ),
    path(
        "staff/services/<int:id>/edit/", admin_service_edit, name="admin_service_edit"
    ),
    path(
        "staff/services/<int:id>/delete/",
        admin_service_delete,
        name="admin_service_delete",
    ),
    path("staff/content/home/", admin_home_content, name="admin_home_content"),
    path(
        "staff/content/home/features/create/",
        admin_home_feature_create,
        name="admin_home_feature_create",
    ),
    path(
        "staff/content/home/features/<int:id>/edit/",
        admin_home_feature_edit,
        name="admin_home_feature_edit",
    ),
    path(
        "staff/content/home/features/<int:id>/delete/",
        admin_home_feature_delete,
        name="admin_home_feature_delete",
    ),
    path("staff/content/about/", admin_about_content, name="admin_about_content"),
    path(
        "staff/content/about/values/create/",
        admin_about_value_create,
        name="admin_about_value_create",
    ),
    path(
        "staff/content/about/values/<int:id>/edit/",
        admin_about_value_edit,
        name="admin_about_value_edit",
    ),
    path(
        "staff/content/about/values/<int:id>/delete/",
        admin_about_value_delete,
        name="admin_about_value_delete",
    ),
    # Admin Package Management
    path("staff/packages/", admin_package_list, name="admin_package_list"),
    path("staff/packages/create/", admin_package_create, name="admin_package_create"),
    path(
        "staff/packages/<int:id>/edit/", admin_package_edit, name="admin_package_edit"
    ),
    path(
        "staff/packages/<int:id>/delete/",
        admin_package_delete,
        name="admin_package_delete",
    ),
    path(
        "staff/packages/<int:id>/view/",
        admin_package_detail,
        name="admin_package_detail",
    ),
    path(
        "staff/packages/service-charge/",
        admin_service_charge_update,
        name="admin_service_charge_update",
    ),
    path("packages/", package, name="package"),
    # ADDONS
    path("staff/addons/create/", admin_addon_create, name="admin_addon_create"),
    path("staff/addons/<int:id>/edit/", admin_addon_edit, name="admin_addon_edit"),
    path(
        "staff/addons/<int:id>/delete/", admin_addon_delete, name="admin_addon_delete"
    ),
    path("staff/addons/<int:id>/view/", admin_addon_detail, name="admin_addon_detail"),
    # ADDITIONAL ONLY
    path(
        "staff/additional/create/",
        admin_additional_create,
        name="admin_additional_create",
    ),
    path(
        "staff/additional/<int:id>/edit/",
        admin_additional_edit,
        name="admin_additional_edit",
    ),
    path(
        "staff/additional/<int:id>/delete/",
        admin_additional_delete,
        name="admin_additional_delete",
    ),
    path(
        "staff/additional/<int:id>/view/",
        admin_additional_detail,
        name="admin_additional_detail",
    ),
    # AI Features
    path("api/chat/", chat_api, name="chat_api"),
    path("api/chat/history/", chat_history, name="chat_history"),
    path("api/chat/sessions/", chat_sessions, name="chat_sessions"),
    path("api/chat/clear/", chat_clear, name="chat_clear"),
    # Customer Notifications
    path(
        "notifications/<int:id>/read/",
        mark_customer_notification_read,
        name="mark_customer_notification_read",
    ),
    path(
        "notifications/clear-all/",
        clear_all_notifications,
        name="clear_all_notifications",
    ),
    # Admin Gallery Management
    path("staff/gallery/", admin_gallery, name="admin_gallery"),
    path(
        "staff/gallery/category/create/",
        admin_gallery_category_create,
        name="admin_gallery_category_create",
    ),
    path(
        "staff/gallery/category/<int:id>/edit/",
        admin_gallery_category_edit,
        name="admin_gallery_category_edit",
    ),
    path(
        "staff/gallery/category/<int:id>/delete/",
        admin_gallery_category_delete,
        name="admin_gallery_category_delete",
    ),
    path(
        "staff/gallery/image/create/",
        admin_gallery_image_create,
        name="admin_gallery_image_create",
    ),
    path(
        "staff/gallery/image/<int:id>/view/",
        admin_gallery_image_detail,
        name="admin_gallery_image_detail",
    ),
    path(
        "staff/gallery/image/<int:id>/edit/",
        admin_gallery_image_edit,
        name="admin_gallery_image_edit",
    ),
    path(
        "staff/gallery/image/<int:id>/delete/",
        admin_gallery_image_delete,
        name="admin_gallery_image_delete",
    ),
    # Admin Canvas Assets Management
    path("staff/canvas-assets/", admin_canvas_assets, name="admin_canvas_assets"),
    path(
        "staff/canvas-assets/category/create/",
        admin_canvas_category_create,
        name="admin_canvas_category_create",
    ),
    path(
        "staff/canvas-assets/category/<int:id>/edit/",
        admin_canvas_category_edit,
        name="admin_canvas_category_edit",
    ),
    path(
        "staff/canvas-assets/category/<int:id>/delete/",
        admin_canvas_category_delete,
        name="admin_canvas_category_delete",
    ),
    path(
        "staff/canvas-assets/label/create/",
        admin_canvas_label_create,
        name="admin_canvas_label_create",
    ),
    path(
        "staff/canvas-assets/label/<int:id>/edit/",
        admin_canvas_label_edit,
        name="admin_canvas_label_edit",
    ),
    path(
        "staff/canvas-assets/label/<int:id>/delete/",
        admin_canvas_label_delete,
        name="admin_canvas_label_delete",
    ),
    path(
        "staff/canvas-assets/asset/create/",
        admin_canvas_asset_create,
        name="admin_canvas_asset_create",
    ),
    path(
        "staff/canvas-assets/asset/<int:id>/view/",
        admin_canvas_asset_detail,
        name="admin_canvas_asset_detail",
    ),
    path(
        "staff/canvas-assets/asset/<int:id>/edit/",
        admin_canvas_asset_edit,
        name="admin_canvas_asset_edit",
    ),
    path(
        "staff/canvas-assets/asset/<int:id>/delete/",
        admin_canvas_asset_delete,
        name="admin_canvas_asset_delete",
    ),
    # Payment System
    path("booking/<int:booking_id>/payment/", payment_page, name="payment_page"),
    path(
        "booking/<int:booking_id>/payment/submit/",
        submit_payment,
        name="submit_payment",
    ),
    path(
        "booking/<int:booking_id>/payment/success/",
        payment_success,
        name="payment_success",
    ),
    path(
        "booking/<int:booking_id>/payment/cancel/",
        payment_cancel,
        name="payment_cancel",
    ),
    # Admin Payment Management
    path("staff/payments/", admin_payment_list, name="admin_payment_list"),
    path(
        "staff/payments/<int:id>/detail/",
        admin_payment_detail,
        name="admin_payment_detail",
    ),
    path(
        "staff/payments/<int:id>/<str:action>/",
        admin_payment_action,
        name="admin_payment_action",
    ),
    path("staff/gcash-config/", admin_gcash_config, name="admin_gcash_config"),
    # PayMongo
    path("booking/<int:booking_id>/paymongo/checkout/", create_paymongo_checkout, name="create_paymongo_checkout"),
    path("booking/<int:booking_id>/paymongo/success/", paymongo_success, name="paymongo_success"),
    path("booking/<int:booking_id>/paymongo/cancel/", paymongo_cancel, name="paymongo_cancel"),
    path("api/paymongo/webhook/", paymongo_webhook, name="paymongo_webhook"),
]
